name: Lint check
on: 
  push:
    branches:
      - 'main'
    paths:
        - '**/*.js'
        - '**/*.ejs'
  pull_request:
    types: 
      - opened
    branches: 
      - 'main'
    paths:
        - '**/*.js'
        - '**/*.ejs'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint